# Generated by Django 5.2.7 on 2025-11-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_staff_alter_user_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userauthprovideraccounts",
            name="user",
        ),
        migrations.DeleteModel(
            name="RefreshToken",
        ),
        migrations.DeleteModel(
            name="UserAuthProviderAccounts",
        ),
    ]
